version: '3'
services:
  relay:
    image: ghcr.io/miss-key/aode-relay:edge
    volumes:
      - ./data:/mnt/
    ports:
      - 8080:8080
    environment:
      - ADDR=0.0.0.0
      - HOSTNAME=relay.misskey.gg
      - HTTPS=true
      - RESTRICTED_MODE=false
      - DEBUG=false
      - VALIDATE_SIGNATURES=true
      - PRETTY_LOG=false
      - PUBLISH_BLOCKS=true
      - SLED_PATH=/mnt/sled/db-0.34
      - RUST_LOG=warn
      - LOCAL_DOMAINS=misskey.gg
      - LOCAL_BLURB="<p>This server is running stably in the Japanese cloud.</p>"
    restart: always
