name: Build container image
on:
  workflow_dispatch:
  push:
    branches:
      - 'interstellar-next'
      - 'interstellar-dev'
    tags:
      - 'v*interstellar*'
  pull_request:
    paths:
      - .github/workflows/build-image.yml
      - Dockerfile

permissions:
  contents: read
  packages: write

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2.3.0
        with:
          platforms: linux/amd64,linux/arm64
      - name: Log in to the Github Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: github.event_name != 'pull_request'
      - uses: docker/metadata-action@v4
        id: meta
        with:
          images: ghcr.io/${{ github.repository }}
          flavor: |
            latest=auto
          tags: |
            type=edge,branch=interstellar-next
            type=edge,branch=interstellar-dev
            type=semver,pattern={{raw}}
            type=ref,event=pr
      - uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=registry,ref=interstellarflights/aode-relay:edge
          cache-to: type=inline
